### ISSUE TITLE
I Don’t Think This Does What You Think It Does

### ISSUE THREAD

**Issue by ldo** [Elreenys/array_tools#1]
In `at_operators.py`, there is this line:

    if (offset[0] and offset[1] and offset[2]) == 100.0:

My guess is, you are trying to ensure that all three `offset` components are equal to 100. But that won’t work: what it is [really doing](https://docs.python.org/3/reference/expressions.html#boolean-operations) is checking that the first two components are nonzero (actually non-equivalent-to-`False`) and that the third one is equal to 100.

**Comment by Elreenys** [comment]
Thanks to point me that, I will correct it.
